// Axon Brain Data — auto-generated by scanner.py v9.0
// Do not edit manually. Run: python3 graph/scanner.py
window.BRAIN_DATA = {
  "nodes": [
    {
      "id": "dashboard.md",
      "label": "dashboard",
      "group": "unknown",
      "path": "dashboard.md",
      "weight": 40,
      "is_blindspot": false,
      "summary": "Hippocampus/Sensory Input — Drop raw data or set operational intent here."
    },
    {
      "id": "episodic_log.md",
      "label": "episodic_log",
      "group": "unknown",
      "path": "episodic_log.md",
      "weight": 40,
      "is_blindspot": false,
      "summary": "Chronological anchor point. Logs all operations and sessions."
    },
    {
      "id": "index.md",
      "label": "index",
      "group": "unknown",
      "path": "index.md",
      "weight": 40,
      "is_blindspot": false,
      "summary": "Semantic map of all knowledge nodes. Used for context-efficient navigation."
    },
    {
      "id": "neocortex/INDEX.md",
      "label": "Neocortex — Memory Palace Lobby",
      "group": "unknown",
      "path": "neocortex/INDEX.md",
      "weight": 100,
      "is_blindspot": false,
      "summary": "The spatial hub of all structured knowledge. Navigate by Room."
    }
  ],
  "links": [
    {
      "source": "dashboard.md",
      "target": "episodic_log.md",
      "type": "sibling"
    },
    {
      "source": "episodic_log.md",
      "target": "index.md",
      "type": "sibling"
    },
    {
      "source": "index.md",
      "target": "neocortex/INDEX.md",
      "type": "sibling"
    }
  ],
  "settings": {
    "visuals": {
      "theme": "nebula",
      "node_glow": true,
      "simulation_speed": "fluid",
      "labels": "hover_only",
      "auto_refresh_seconds": 5
    },
    "colors": {
      "left_hemisphere": "#00FFFF",
      "right_hemisphere": "#FF00FF",
      "wiki_page": "#FFFF00",
      "blindspot": "#FF3300",
      "system": "#FFFFFF"
    },
    "physics": {
      "repel_force": -300,
      "link_distance": 100,
      "center_gravity": 0.5,
      "collision_radius": 30
    }
  },
  "docs": {}
};
